bdfi/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include

from bdfi import settings
from movie import views as movie_views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/profile/', movie_views.UserProfile.as_view(), name='account_profile'),
    url(r'^accounts/', include('allauth.urls')),

    path('', movie_views.home, name='home'),
    path('movie/', include('movie.urls', namespace='movie')),
    path('news/', include('news.urls', namespace='news')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

movie/urls.py
from django.conf.urls import url
from django.urls import path

from movie import views, autocompletes

app_name = 'movie'
urlpatterns = [
    url(r'^movie-title/$', autocompletes.MovieTitleAutocomplete.as_view(), name='movie_title_autocomplete'),
    path('<int:pk>/', views.FilmDetail.as_view(), name='detail'),
    path('new/', views.CreateMovie.as_view(), name='new_movie'),
    path('tv/', views.TVList.as_view(), name='tv_list'),
    path('actor/<int:pk>/', views.ActorDetail.as_view(), name='actor_detail'),
    path('actor/', views.ActorList.as_view(), name='actor_list'),
    path('', views.MovieList.as_view(), name='movie_list'),
]

news/urls.py
from django.urls import path

from news import views

app_name = 'news'
urlpatterns = [
    path('<int:pk>/', views.NewsDetail.as_view(), name='detail'),
    path('', views.NewsList.as_view(), name='list'),
]

movie/models.py
from django.contrib.auth.models import User
from django.db import models
from embed_video.fields import EmbedVideoField


class Location(models.Model):
    city = models.CharField(max_length=64)
    province = models.CharField(max_length=64)

    def __str__(self):
        return self.city


class Genre(models.Model):
    name = models.CharField(max_length=32)

    def __str__(self):
        return self.name


class Role(models.Model):
    name = models.CharField(max_length=128)

    def __str__(self):
        return self.name


class ProductionHouse(models.Model):
    name = models.CharField(max_length=128)

    def __str__(self):
        return self.name


class Movie(models.Model):
    FILM = 'film'
    TV_SERIES = 'tv'
    FTV = 'ftv'
    CATEGORY_CHOICES = (
        (FILM, 'Film'),
        (TV_SERIES, 'TV'),
        (FTV, 'FTV')
    )
    title = models.CharField(max_length=255)
    release_date = models.DateField()
    production_house = models.ForeignKey(ProductionHouse, on_delete=models.CASCADE)
    category = models.CharField(max_length=32, choices=CATEGORY_CHOICES, default=FILM)
    genre = models.ManyToManyField(Genre)
    video = EmbedVideoField(null=True)
    synopsis = models.TextField(null=True)

    def __str__(self):
        return self.title


class Actor(models.Model):
    name = models.CharField(max_length=128)
    fullname = models.CharField(max_length=255)
    birth_of_date = models.DateField()
    place_of_birth = models.ForeignKey(Location, on_delete=models.CASCADE)
    role = models.ManyToManyField(Role)
    biography = models.TextField()

    def __str__(self):
        return self.name


class Cast(models.Model):
    actor = models.ForeignKey(Actor, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    play_as = models.CharField(max_length=128)

    def __str__(self):
        return self.play_as


class Credit(models.Model):
    name = models.CharField(max_length=128)
    role = models.ForeignKey(Role, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Trivia(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    info = models.CharField(max_length=255)
    link = models.URLField()
    source = models.CharField(max_length=128)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.info


class Review(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    rating = models.SmallIntegerField()
    comment = models.TextField()

    def __str__(self):
        return self.rating

news/models.py
from django.contrib.auth.models import User
from django.db import models


class News(models.Model):
    title = models.CharField(max_length=255, unique=True)
    publish_date = models.DateTimeField()
    author = models.ForeignKey(User, on_delete=models.PROTECT)
    content = models.TextField()

    def __str__(self):
        return self.title

movie/forms.py
from dal import autocomplete
from django import forms

from movie.models import Movie


class MovieForm(forms.ModelForm):
    title = autocomplete.Select2ListCreateChoiceField(widget=autocomplete.ListSelect2(url='movie:movie_title_autocomplete'))

    class Meta:
        model = Movie
        fields = ('__all__')

movie/views.py
from django.contrib.auth.models import User
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import DetailView, ListView, UpdateView, CreateView

from movie import forms
from movie.models import Movie, Genre, Actor, Cast
from news.models import News


def home(request):
    feature_actor = Actor.objects.order_by('?').first()
    feature_news = News.objects.order_by('-id')[:3]
    feature_films = Movie.objects.order_by('?')[:3]
    hot_films = Movie.objects.order_by('-release_date')[:10]
    genre_list = Genre.objects.order_by('?')
    context = {
        'feature_actor': feature_actor,
        'feature_films': feature_films,
        'hot_films': hot_films,
        'feature_news': feature_news,
        'genre_list': genre_list,
    }
    return render(request, 'movie/index.html', context)


class UserProfile(UpdateView):
    fields = ['first_name', 'last_name', 'email']
    template_name = 'account/profile.html'
    success_url = reverse_lazy('account_profile')

    def get_object(self):
        return get_object_or_404(User, pk=self.request.user.id)


class FilmDetail(DetailView):
    model = Movie
    template_name = 'movie/movie_detail.html'

    def get_context_data(self, **kwargs):
        context = super(FilmDetail, self).get_context_data(**kwargs)
        casted_actor = Cast.objects.filter(movie=self.object).order_by('?').first()
        context['casted_actor'] = casted_actor.actor
        return context


class CreateMovie(CreateView):
    model = Movie
    form_class = forms.MovieForm
    template_name = 'movie/movie_form.html'
    success_url = reverse_lazy('movie:movie_list')


class MovieList(ListView):
    model = Movie
    template_name = 'movie/movie_list.html'
    queryset = Movie.objects.filter(category=Movie.FILM)


class ActorDetail(DetailView):
    model = Actor
    template_name = 'movie/actor_detail.html'


class TVList(ListView):
    model = Movie
    template_name = 'movie/tv_list.html'
    queryset = Movie.objects.filter(category=Movie.TV_SERIES)


class ActorList(ListView):
    model = Actor
    template_name = 'movie/actor_list.html'

news/views.py
from django.views.generic import ListView, DetailView

from news import models


class NewsList(ListView):
    model = models.News
    template_name = 'news/news_list.html'


class NewsDetail(DetailView):
    model = models.News
    template_name = 'news/news_detail.html'

movie/templates/movie/actor_detail.html
{% extends 'movie/index.html' %}
{% load static embed_video_tags debug_tags %}
{% block page_content %}
    <div class="container">
        {% block widgets %}
        {{ block.super }}
        {% endblock widgets %}
        {% block main_content %}
      <div class="blog-header">
        <h1 class="blog-title">{{ actor.name }}</h1>
        <p class="lead blog-description">{{ actor.birth_of_date }}</p>
      </div>

    </div><!-- /.container -->
    <main role="main" class="container">
          <div class="row">
              <div class="col-md-8 blog-main">
                  <div class="blog-post">
                    <table>
                        <tr><th>Nama lengkap</th><td>&nbsp;</td><td>{{ actor.fullname }}</td></tr>
                        <tr><th>Tempat lahir</th><td>&nbsp;</td><td>{{ actor.place_of_birth }}</td></tr>
                        {% for role in actor.role_set.all %}
                            <tr><th>Profesi</th><td>&nbsp;</td><td>{{ role.name }}</td></tr>
                        {% endfor %}
                    </table>
                      <hr>
                      <p>{{ actor.biography }}</p>
                    <h2>Film</h2>
                      <table>
                          {% for cast in actor.cast_set.all %}
                              {% if cast.actor == actor %}
                                  <tr><td><a href="{% url 'movie:detail' cast.movie.id %}">{{ cast.movie }}</a></td><td> -> </td><td>{{ cast.play_as }}</td></tr>
                              {% endif %}
                          {% endfor %}
                      </table>
                  </div><!-- /.blog-post -->
              </div>
              <aside class="col-md-4 blog-sidebar">
                  {% block sidebar %}
                  <div class="p-3 bg-light rounded">
                      <h3>Synopsis</h3>
                      <p>{{ movie.synopsis }}</p>
                  </div>
                  <div class="p-3">
                      <h3>Archives</h3>
                      <ol class="list-unstyled">
                          <li><a href="#">March 2014</a></li>
                          <li><a href="#">February 2014</a></li>
                          <li><a href="#">January 2014</a></li>
                          <li><a href="#">December 2013</a></li>
                          <li><a href="#">November 2013</a></li>
                          <li><a href="#">October 2013</a></li>
                          <li><a href="#">September 2013</a></li>
                          <li><a href="#">August 2013</a></li>
                          <li><a href="#">July 2013</a></li>
                          <li><a href="#">June 2013</a></li>
                          <li><a href="#">May 2013</a></li>
                          <li><a href="#">April 2013</a></li>
                      </ol>
                  </div>
                  <div class="p-3">
                      <h3>Elsewhere</h3>
                      <ol class="list-unstyled">
                          <li><a href="#">GitHub</a></li>
                          <li><a href="#">Twitter</a></li>
                          <li><a href="#">Facebook</a></li>
                      </ol>
                  </div>
                  {% endblock %}
              </aside>

          </div>

        </main>
{% endblock main_content %}
{% endblock page_content %}

movie/templates/movie/actor_list.html
{% extends 'movie/index.html' %}
{% load embed_video_tags %}
{% block page_content %}
<div class="container">
    {% block widgets %}
    {{ block.super }}
    {% endblock widgets %}
</div>
{% block main_content %}
<main role="main" class="container">
    <div class="row">
        <div class="col-md-8 blog-main">
            {% for actor in actor_list %}
            <div class="blog-post">
                <h2 class="blog-post-title"><a href="{% url 'movie:actor_detail' actor.id %}">{{ actor.name }}</a></h2>
                <p class="blog-post-meta">{{ actor.birth_of_date }}</p>
            </div><!-- /.blog-post -->
            {% endfor %}

          <nav class="blog-pagination">
            <a class="btn btn-outline-primary" href="#">Older</a>
            <a class="btn btn-outline-secondary disabled" href="#">Newer</a>
          </nav>

        </div><!-- /.blog-main -->

        <aside class="col-md-4 blog-sidebar">
              {% block sidebar %}
                    {{ block.super }}
              {% endblock %}
        </aside><!-- /.blog-sidebar -->

      </div><!-- /.row -->

    </main><!-- /.container -->
{% endblock main_content %}
    {% endblock page_content %}

movie/templates/movie/index.html
<!doctype html>
{% load static embed_video_tags %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">
    <title>Basisdata Film Indonesia</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:700,900" rel="stylesheet">
    <link href="{% static 'movie/css/blog.css' %}" rel="stylesheet">
</head>
<body>
{% block page_content %}
    <div class="container">
        {% block widgets %}
        <header class="blog-header py-3">
            <div class="row flex-nowrap justify-content-between align-items-center">
                <div class="col-10 text-left">
                    <a class="blog-header-logo text-dark" href="{% url 'home' %}">BdFI</a>
                </div>
                {% if not user.is_authenticated %}
                <div class="col-1 pt-1">
                    <a class="btn btn-sm btn-outline-secondary" href="{% url 'account_signup' %}">Daftar</a>
                </div>
                <div class="col-1 d-flex justify-content-end align-items-center">
                    <a class="btn btn-sm btn-outline-secondary" href="{% url 'account_login' %}">Login</a>
                </div>
                {% else %}
                <div class="col-1 pt-1">
                    <a class="btn btn-sm btn-outline-secondary" href="{% url 'account_profile' %}">{{ user.username }}</a>
                </div>
                <div class="col-1 d-flex justify-content-end align-items-center">
                    <a class="btn btn-sm btn-outline-secondary" href="{% url 'account_logout' %}">Logout</a>
                </div>
                {% endif %}
            </div>
        </header>

        <div class="nav-scroller py-1 mb-2">
            <nav class="nav d-flex justify-content-between">
                <a class="p-2 text-muted" href="{% url 'home' %}">Home</a>
                <a class="p-2 text-muted" href="{% url 'news:list' %}">News</a>
                <a class="p-2 text-muted" href="{% url 'movie:movie_list' %}">Film</a>
                <a class="p-2 text-muted" href="{% url 'movie:tv_list' %}">Sinetron</a>
                <a class="p-2 text-muted" href="{% url 'movie:actor_list' %}">Actor</a>
            </nav>
        </div>
        {% endblock widgets %}

        {% block main_content %}
        <div class="row mb-2">
            {% for film in feature_films %}
            <div class="col-md-4">
                <div class="card flex-md-row mb-4 shadow-sm h-md-250">
                    <div class="card-body d-flex flex-column align-items-start">
                        {% video film.video '310x250' %}
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        {% endblock main_content %}
    </div>

    <main role="main" class="container">
        <div class="row">
            <div class="col-md-8 blog-main">
                <h3 class="pb-3 mb-4 font-italic border-bottom">Berita Terbaru</h3>
                {% for info in feature_news %}
                <div class="blog-post">
                    <h2 class="blog-post-title"><a href="{% url 'news:detail' info.id %}">{{ info.title }}</a></h2>
                    <p class="blog-post-meta">{{ info.publish_date }}</p>
                    <p>{{ info.content|truncatewords:20 }}</p>
                </div><!-- /.blog-post -->
                {% endfor %}
            </div><!-- /.blog-main -->

            <aside class="col-md-4 blog-sidebar">
                {% block sidebar %}
                <div class="p-3 mb-3 bg-light rounded">
                    <h4 class="font-italic"><a href="{% url 'movie:actor_detail' feature_actor.id %}">{{ feature_actor.name }}</a></h4>
                    <table>
                        <tr><th>Tempat lahir</th><td>{{ feature_actor.place_of_birth }}</td></tr>
                        <tr><th>Tanggal lahir</th><td>{{ feature_actor.birth_of_date }}</td></tr>
                    </table>
                </div>
                <div class="p-3">
                    <h4 class="font-italic">Film terbaru</h4>
                    <ol class="list-unstyled mb-0">
                        {% for hot_film in hot_films %}
                        <li><a href="{% url 'movie:detail' hot_film.id %}">{{ hot_film.title }}</a></li>
                        {% endfor %}
                    </ol>
                </div>
                {% endblock sidebar %}
            </aside><!-- /.blog-sidebar -->
        </div><!-- /.row -->
    </main><!-- /.container -->
    {% endblock page_content %}
    <footer class="blog-footer">
      <p>Blog template built for <a href="https://getbootstrap.com/">Bootstrap</a> by <a href="https://twitter.com/mdo">@mdo</a>.</p>
      <p>
        <a href="#">Back to top</a>
      </p>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="{% static 'vendor/holderjs/holder.min.js' %}"></script>
    <script>
      Holder.addTheme('thumb', {
        bg: '#55595c',
        fg: '#eceeef',
        text: 'Thumbnail'
      });
    </script>
  </body>
</html>

movie/templates/movie/movie_detail.html
{% extends 'movie/index.html' %}
{% load static embed_video_tags %}
{% block page_content %}
    <div class="container">
        {% block widgets %}
        {{ block.super }}
        {% endblock widgets %}
        {% block main_content %}
      <div class="blog-header">
        <h1 class="blog-title">{{ movie.title }}</h1>
        <p class="lead blog-description">{{ movie.release_date }}</p>
      </div>

    </div><!-- /.container -->
    <main role="main" class="container">
          <div class="row">
              <div class="col-md-8 blog-main">
                  <div class="blog-post">
                      {% video movie.video 'tiny' %}
                    <table>
                        <tr><th>Rumah produksi</th><td>&nbsp;</td><td>{{ movie.production_house }}</td></tr>
                        <tr><th>Tanggal mulai tayang</th><td>&nbsp;</td><td>{{ movie.release_date }}</td></tr>
                        {% for credit in movie.credit_set.all %}
                            <tr><th>{{ credit.role }}</th><td>&nbsp;</td><td>{{ credit.name }}</td></tr>
                        {% endfor %}
                    </table>
                      <hr>
                    <h2>Pemain</h2>
                      <table>
                          {% for cast in movie.cast_set.all %}
                          <tr><td><a href="{% url 'movie:actor_detail' cast.actor.id %}">{{ cast.actor }}</a></td><td> -> </td><td>{{ cast.play_as }}</td></tr>
                          {% endfor %}
                      </table>
                  </div><!-- /.blog-post -->
              </div>
              <aside class="col-md-4 blog-sidebar">
                  {% block sidebar %}
                    <div class="p-3 mb-3 bg-light rounded">
                        <h4 class="font-italic"><a href="{% url 'movie:actor_detail' casted_actor.id %}">{{ casted_actor.name }}</a></h4>
                        <table>
                            <tr><th>Tempat lahir</th><td>{{ casted_actor.place_of_birth }}</td></tr>
                            <tr><th>Tanggal lahir</th><td>{{ casted_actor.birth_of_date }}</td></tr>
                        </table>
                    </div>
                  {% endblock %}
              </aside>

          </div>

        </main>
{% endblock main_content %}
{% endblock page_content %}

movie/templates/movie/movie_form.html
{% extends 'movie/index.html' %}
{% load static embed_video_tags crispy_forms_tags %}
{% block page_content %}
    <div class="container">
        {% block widgets %}
        {{ block.super }}
        {% endblock widgets %}
        {% block main_content %}
      <div class="blog-header">
        <h1 class="blog-title">{{ movie.title }}</h1>
        <p class="lead blog-description">{{ movie.release_date }}</p>
      </div>

    </div><!-- /.container -->
    <main role="main" class="container">
          <div class="row">
              <div class="col-md-8 blog-main">
                  <div class="blog-post">
                      <h2>Data Film Baru</h2>
                      <form class="form" action="" method="post">{% csrf_token %}
                          {{ form|crispy }}
                          <input class="btn btn-primary" type="submit" value="Simpan">
                      </form>
                  </div><!-- /.blog-post -->
              </div>
              <aside class="col-md-4 blog-sidebar">
                  {% block sidebar %}
                    <div class="p-3">
                        <h4 class="font-italic">Basisdata</h4>
                        <ol class="list-unstyled">
                            <li><a href="{% url 'movie:new_movie' %}">Tambah film</a></li>
                            <li><a href="#">Twitter</a></li>
                            <li><a href="#">Facebook</a></li>
                        </ol>
                    </div>
                  {% endblock %}
              </aside>

          </div>

        </main>
<script type="text/javascript" src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>
{{ form.media }}
{% endblock main_content %}
{% endblock page_content %}

movie/templates/movie/movie_list.html
{% extends 'movie/index.html' %}
{% load embed_video_tags %}
{% block page_content %}
<div class="container">
    {% block widgets %}
    {{ block.super }}
    {% endblock widgets %}
</div>
{% block main_content %}
<main role="main" class="container">
    <div class="row">
        <div class="col-md-8 blog-main">
            {% for movie in movie_list %}
            <div class="blog-post">
                <h2 class="blog-post-title"><a href="{% url 'movie:detail' movie.id %}">{{ movie.title }}</a></h2>
                <p class="blog-post-meta">{{ movie.release_date }}</p>
                {% video movie.video as movie_video %}
                <img width="40%" src="{{ movie_video.thumbnail }}">
                {% endvideo %}
            </div><!-- /.blog-post -->
            {% endfor %}

          <nav class="blog-pagination">
            <a class="btn btn-outline-primary" href="#">Older</a>
            <a class="btn btn-outline-secondary disabled" href="#">Newer</a>
          </nav>

        </div><!-- /.blog-main -->

        <aside class="col-md-4 blog-sidebar">
              {% block sidebar %}
              {% endblock %}
        </aside><!-- /.blog-sidebar -->

      </div><!-- /.row -->

    </main><!-- /.container -->
{% endblock main_content %}
    {% endblock page_content %}

movie/templates/movie/tv_list.html
{% extends 'movie/index.html' %}
{% load embed_video_tags %}
{% block page_content %}
<div class="container">
    {% block widgets %}
    {{ block.super }}
    {% endblock widgets %}
</div>
{% block main_content %}
<main role="main" class="container">
    <div class="row">
        <div class="col-md-8 blog-main">
            {% for movie in movie_list %}
            <div class="blog-post">
                <h2 class="blog-post-title"><a href="{% url 'movie:detail' movie.id %}">{{ movie.title }}</a></h2>
                <p class="blog-post-meta">{{ movie.release_date }}</p>
                {% video movie.video as movie_video %}
                <img width="40%" src="{{ movie_video.thumbnail }}">
                {% endvideo %}
            </div><!-- /.blog-post -->
            {% endfor %}

          <nav class="blog-pagination">
            <a class="btn btn-outline-primary" href="#">Older</a>
            <a class="btn btn-outline-secondary disabled" href="#">Newer</a>
          </nav>

        </div><!-- /.blog-main -->

        <aside class="col-md-4 blog-sidebar">
              {% block sidebar %}
                    {{ block.super }}
              {% endblock %}
        </aside><!-- /.blog-sidebar -->

      </div><!-- /.row -->

    </main><!-- /.container -->
{% endblock main_content %}
    {% endblock page_content %}

news/templates/news/news_detail.html
{% extends 'movie/index.html' %}
{% load static embed_video_tags %}
{% block page_content %}
    <div class="container">
        {% block widgets %}
        {{ block.super }}
        {% endblock widgets %}
        {% block main_content %}
      <div class="blog-header">
        <h1 class="blog-title">{{ news.title }}</h1>
        <p class="lead blog-description">{{ news.publish_date }}</p>
      </div>

    </div><!-- /.container -->
    <main role="main" class="container">
          <div class="row">
              <div class="col-md-8 blog-main">
                  <div class="blog-post">
                      {{ news.content }}
                  </div><!-- /.blog-post -->
              </div>
              <aside class="col-md-4 blog-sidebar">
                  {% block sidebar %}
                        {{ block.super }}
                  {% endblock %}
              </aside>

          </div>

        </main>
{% endblock main_content %}
{% endblock page_content %}

news/templates/news/news_list.html
{% extends 'movie/index.html' %}
{% load embed_video_tags %}
{% block page_content %}
<div class="container">
    {% block widgets %}
    {{ block.super }}
    {% endblock widgets %}
</div>
{% block main_content %}
<main role="main" class="container">
    <div class="row">
        <div class="col-md-8 blog-main">
            {% for news in news_list %}
            <div class="blog-post">
                <h2 class="blog-post-title"><a href="{% url 'news:detail' news.id %}">{{ news.title }}</a></h2>
                <p class="blog-post-meta">{{ news.publish_date }}</p>
                <p>{{ news.content | truncatewords:20 }}</p>
            </div><!-- /.blog-post -->
            {% endfor %}

          <nav class="blog-pagination">
            <a class="btn btn-outline-primary" href="#">Older</a>
            <a class="btn btn-outline-secondary disabled" href="#">Newer</a>
          </nav>

        </div><!-- /.blog-main -->

        <aside class="col-md-4 blog-sidebar">
              {% block sidebar %}
                    {{ block.super }}
              {% endblock %}
        </aside><!-- /.blog-sidebar -->

      </div><!-- /.row -->

    </main><!-- /.container -->
{% endblock main_content %}
    {% endblock page_content %}